# ~/.config/starship.toml

add_newline = true
command_timeout = 1000

format = """
$sudo\
$character\
$hostname\
$directory\
$git_branch\
$git_status \
$fill\
$python\
$aws\
$golang\
$java\
$nodejs\
$rust\
$ruby\
$scala\
$dart\
$conda\
$pijul_channel\
$lua\
$rlang\
$package\
$buf\
$memory_usage\
$docker_context\
(#1C3A5E)$cmd_duration [ î‚¶](#1C3A5E)$time[î‚´ ](#1C3A5E)
[>](bold green) """

continuation_prompt = 'â–¶â–¶ '

[username]
style_user='bold white'

[fill]
style = 'white'

[character]
success_symbol = '' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = "âŒ"

[sudo]
disabled = false
format='[$symbol]($style)'

[time]
disabled = false
time_format = "%r" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ó±‘ $time ](bg:#1C3A5E fg:#ffffff)]($style)'

[cmd_duration]
format = '[ $duration](bold yellow)'

# ---

# Shows the hostname
[hostname]
format = '[$ssh_symbol](bold green) '
disabled = false
ssh_symbol = "ğŸŒ "

# Shows current directory
[directory]
truncation_length = 3
fish_style_pwd_dir_length=2
home_symbol = 'ó°° ~'
read_only_style = '197'
read_only = ' ï€£ '
format = '[$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
symbol = "ï˜ "
format = 'on [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = 'â€¦/'
style = 'bold green'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = 'ğŸ³'
up_to_date = ''
untracked = 'ï”© '
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
stashed = 'ï£– '
modified = 'ï„ '
staged = '[++\($count\)](green)'
renamed = 'ïª¶ '
deleted = 'ï€” '


# ---

[php]
format='[ $symbol($version(-$name) )]($style)'
symbol = "î˜ˆ "

[aws]
symbol = "îŒ½  "
format='[ $symbol($version(-$name) )]($style)'

[buf]
symbol = "ï’ "
format='[ $symbol($version(-$name) )]($style)'

[c]
symbol = "î˜ "
format='[ $symbol($version(-$name) )]($style)'

[conda]
symbol = "ï„Œ "
format='[ $symbol($version(-$name) )]($style)'

[dart]
symbol = "î˜ "
format='[ $symbol($version(-$name) )]($style)'

[docker_context]
symbol = "ïŒˆ "
format='[ $symbol($version(-$name) )]($style)'

[golang]
symbol = "î˜§ "
format='[ $symbol($version(-$name) )]($style)'

[java]
symbol = "î‰– "
format='[ $symbol($version(-$name) )]($style)'

[lua]
symbol = "î˜  "
format='[ $symbol($version(-$name) )]($style)'

[memory_usage]
symbol = "ó°› "
disabled = true
style='bold dimmed white'
threshold = 1
format = "$symbol [${ram}(|${swap})]($style) "

[nodejs]
symbol = "îœ˜ "
format='[ $symbol($version(-$name) )]($style)'

[package]
symbol = "ó°— "
format='[ $symbol($version(-$name) )]($style)'

[pijul_channel]
symbol = "ï˜ "
format='[ $symbol($version(-$name) )]($style)'

[python]
pyenv_version_name = true
format='[ $symbol($version(-$name))(\($virtualenv\) )]($style)'

[ruby]
symbol = "î‘ "
format='[ $symbol($version(-$name) )]($style)'

[rlang]
format='[ $symbol($version(-$name) )]($style)'

[rust]
symbol = "î¨ "
format='[ $symbol($version(-$name) )]($style)'

[scala]
symbol = "îœ· "
format='[ $symbol($version(-$name) )]($style)'
